<?php
/**
 * Script para importar peças faltantes da planilha
 * Gerado automaticamente
 */

header('Content-Type: application/json');

// Conexão com banco
$host = '187.49.226.10';
$db = 'f137049_in9aut';
$user = 'f137049_tool';
$pass = 'In9@1234qwer';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4", $user, $pass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    die(json_encode(['error' => 'Conexão falhou: ' . $e->getMessage()]));
}

// Peças para importar
$pecas = [
    ['codigo' => 'IMP-ACE-0138', 'nome' => 'CHAVE LIMPADOR P/BRISA VW DELIVERY', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0357', 'nome' => 'LIMPADOR PARABRISA (PAR) L200', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0428', 'nome' => 'PALHETA 16 POL H622', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0429', 'nome' => 'PALHETA 18 POL SILICONE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0430', 'nome' => 'PALHETA 24 - DYNA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0431', 'nome' => 'PALHETA AEROFLAT DT 24P - 80400 WW 11.180', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0432', 'nome' => 'PALHETA WM 11180(LIMPADOR PARABRISA)', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0433', 'nome' => 'PAR PALHETA HILLUX', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0434', 'nome' => 'PAR PALHETA YN-PS1332 - CINOY', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0665', 'nome' => 'SUPORTE RETROVISOR - STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0776', 'nome' => 'RETROVISOR ESPORTIVO RITZ CORES ALLEN', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0804', 'nome' => 'PALHETA LIMPADOR  2000', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0946', 'nome' => 'PALHETA LIMPADOR DIANT. PF 22 POL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-0947', 'nome' => 'PALHETA LIMPADOR DIANT. PF 24 POL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ACE-1029', 'nome' => 'PALHETA RDX32 TOTALCLIP FLEX 24 10 ENC', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ARR-0383', 'nome' => 'MANG INF RADIADOR - STRADA', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-ARR-0385', 'nome' => 'MANG SUP RADIADOR - STRADA', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-ARR-0492', 'nome' => 'RADIADOR STRADA', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-ARR-0529', 'nome' => 'RESERVATÓRIO DE AGUA RADIADOR - M.BENZ ATEGO 2430', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-ARR-0732', 'nome' => 'RESERVATÓRIO DE ÁGUA DO RADIADOR - FIAT STRADA', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-ARR-0753', 'nome' => 'CONEXÃO RADIADOR', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-ARR-0754', 'nome' => 'LIMPA RADIADOR', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-ARR-0783', 'nome' => 'MANGUEIRA ESPAGUETE CORUGADO 1/2 12MM', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-ARR-0787', 'nome' => 'VENTOINHA DO RADIADOR', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-ARR-0824', 'nome' => 'MANGUEIRA HIDRAULICA  SAE 100 R2AT 5/16 - ST', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-ARR-0829', 'nome' => 'MANGUEIRA HIDRAULICA  SAE 100 R2AT 1/2 - ST', 'categoria' => 'arrefecimento'],
    ['codigo' => 'IMP-CAR-0435', 'nome' => 'PARACHOQUE STRADA PRETO TEXTURIZADO 02/1202/062280 CBC/R2A', 'categoria' => 'geral'],
    ['codigo' => 'IMP-CAR-0487', 'nome' => 'PORTA FUZIVEL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-CAR-0909', 'nome' => 'JOGO CANALETA PORTA DIREITA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-CAR-0929', 'nome' => 'PARACHOQUE MVL MONT PBT 10.00 A 23 50 T ST700 3MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-CAR-0931', 'nome' => 'FAIXA PARACHOQUE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-CAR-1080', 'nome' => 'CAPOTA MARITIMA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-ELE-0025', 'nome' => 'ALTERNADOR GM CLASSIC - VALEO', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0026', 'nome' => 'ALTERNADOR P/ VEICULO AUTOMOVEL', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0027', 'nome' => 'ALTERNADOR STRADA 21 F000BL062E -SEG', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0076', 'nome' => 'BATERIA 100 AMP F30AGE - KONDOR', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0077', 'nome' => 'BATERIA 150 AMP - ZETTA 12V CORRENTE DE PARTIDA 900A', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0078', 'nome' => 'BATERIA 50 AMP - MEGATEC', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0079', 'nome' => 'BATERIA 60 AMP - KONDOR', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0080', 'nome' => 'BATERIA 60 AMP - PARALELA', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0081', 'nome' => 'BATERIA 60 AMP - ZETTA Z60D', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0082', 'nome' => 'BATERIA 60 AMP F22AD - KONDOR', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0151', 'nome' => 'CONECTOR FAROL FIAT', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0152', 'nome' => 'CONECTOR SOQUETE FAROL 2VIAS FORD', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0201', 'nome' => 'FAROL AUXILIAR 09LEDS 12/24V 27W REDONDO FINO', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0317', 'nome' => 'LAMPADA  FAROL H11', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0318', 'nome' => 'LAMPADA 1034 24V 21/5W', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0319', 'nome' => 'LAMPADA 1141 12V 21 W LARANJA 1 POLO ENCONTRADO', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0320', 'nome' => 'LAMPADA 1141 12V P21W 1 POLO UNIVERSAL - GL1141', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0321', 'nome' => 'LAMPADA 1141 24V P21W UNIVERSAL', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0322', 'nome' => 'LAMPADA 1141 28W 1P AMARELO PINO DESENCONT', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0323', 'nome' => 'LAMPADA 2 POLOS', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0324', 'nome' => 'LAMPADA 67 - 24V', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0325', 'nome' => 'LAMPADA 69 24V T4W', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0326', 'nome' => 'LAMPADA DE RÉ', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0327', 'nome' => 'LAMPADA ESMAGADA 24V 5W PINGO', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0328', 'nome' => 'LAMPADA FAROL H7/24V', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0329', 'nome' => 'LAMPADA H1 12V 55W COMUM', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0330', 'nome' => 'LAMPADA H1 55W FAROL MILHA', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0331', 'nome' => 'LAMPADA H11 12V 55W TESLLA', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0332', 'nome' => 'LAMPADA H4 - 24V', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0333', 'nome' => 'LAMPADA H4 12V', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0334', 'nome' => 'LAMPADA H4 12V - BOSCH', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0335', 'nome' => 'LAMPADA H4 12V - MAGNETI MARELLI', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0336', 'nome' => 'LAMPADA H4 MM - 12V', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0337', 'nome' => 'LAMPADA H7 - 12V 55W', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0338', 'nome' => 'LAMPADA H7 - 24V', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0339', 'nome' => 'LAMPADA HB3 12V/60W 9005 60W', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0340', 'nome' => 'LAMPADA HB4 12V 51W 9006', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0341', 'nome' => 'LAMPADA PINGAO 12067CP', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0342', 'nome' => 'LAMPADA PINGAO 921 T15 12V 16W - CINOY', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0343', 'nome' => 'LAMPADA PINGAO 922 12V 16W LARANJA - HBL', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0344', 'nome' => 'LAMPADA PINGAO FAROLETE', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0345', 'nome' => 'LAMPADA PY21W DIANTEIRA', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0346', 'nome' => 'LAMPADA SETA TRASEIRA', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0347', 'nome' => 'LAMPADA T10 PINGO 5 LED 12V', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0561', 'nome' => 'SENSOR ROTACAO MONTANA', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0562', 'nome' => 'SENSOR TEMPERATURA', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0587', 'nome' => 'SOQUETE FAROL UNIVERSAL (FIO 1,50 MM)', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0588', 'nome' => 'SOQUETE LAMPADA FAROL H7', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0724', 'nome' => 'BATERIA 60AH - STRADA', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0733', 'nome' => 'SENSOR SONDA LAMBDA PÓS', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0734', 'nome' => 'SENSOR ABS DIANT. LD', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0735', 'nome' => 'RELE ALTERNADOR', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0739', 'nome' => 'SENSOR SONDA LAMBDA DO CATALISADOR', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0740', 'nome' => 'BATERIA 70H - CCA 660', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0748', 'nome' => 'LAMPADA 1141 21W 24V - TESLLA', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0749', 'nome' => 'LAMPADA 1034 24V TESLLA 2 POLOS', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0771', 'nome' => 'FUSIVEL DE LAMINA 15A AZUL', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0778', 'nome' => 'LAMPADA FAROL TITAN 150.160', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0778', 'nome' => 'LAMPADA 1141 HALOWAY 24V', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0798', 'nome' => 'LAMPADA GL 2825W5W 12V - GAUSS', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0884', 'nome' => 'LAMPADA P/LANT.UNI 5W/12V', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0890', 'nome' => 'SENSOR DE TEMPERATURA PLUG ELETRONICO', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0922', 'nome' => 'LAMPADA ESMAGADA 12V 5W PINGO', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0940', 'nome' => 'FUSIVEL LAMINA TODO', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0942', 'nome' => 'LAMPADA 67/12', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0944', 'nome' => 'LAMPADA 1141 24VOLT', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0951', 'nome' => 'LAMPADA 67 24 VOLT', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0952', 'nome' => 'LAMPADA BULBO 24 VLT', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0953', 'nome' => 'LAMPADA 1034 24 VOL', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-0954', 'nome' => 'MINI RELE 24 VT', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-1011', 'nome' => 'LAMPADA PINGO - PLACA E FAROL DIANTEIRO', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-1030', 'nome' => 'LAMPADA PINGÃO SUPER 16W / 12V', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-1062', 'nome' => 'TOMADA PARA SENSOR 4 PINOS REDONDO', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-1067', 'nome' => 'LAMPADA PINGO PLACA', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-1089', 'nome' => 'HIDROOVÁCUO S/ SENSOR', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-1099', 'nome' => 'MANGOTE ALTERNADOR', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-2011', 'nome' => 'RELE AUXILIAR 12V 4 T C/SUP 40A V/GM/AUDI/IVECO', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-2012', 'nome' => 'CHICOTE BASE P/ RELES 5 VIAS UNIVERSAL ETE 7595', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ELE-2015', 'nome' => 'SENSOR PEDAL DA EMBREAGEM - LUZ DO SENSOR', 'categoria' => 'eletrica'],
    ['codigo' => 'IMP-ESC-0001', 'nome' => 'ABAFADOR INTERMEDIÁRIO STRADA 21', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-0378', 'nome' => 'LUVA - TUBO ESCAPAMENTO STRADA 21', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-0578', 'nome' => 'SILENCIOSO - STRADA', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-0586', 'nome' => 'SONDA LAMBDA PRÉ CATALISADOR - BOSCH', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-0737', 'nome' => 'CATALISADOR', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-0745', 'nome' => 'SUPORTE DE ESCAPAMENTO', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-0764', 'nome' => 'ABAFADOR GM CELTA 110 06 INTERM', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-0765', 'nome' => 'SILENCIOSO TRAS CORSA CLASSIC', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-0869', 'nome' => 'ESCAPAMENTO FLEXIVEL COM SONDA', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-0870', 'nome' => 'ESCAPAMENTO INTERMEDIARIO', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-0872', 'nome' => 'ESCAPAMENTO TRASEIRO', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-1093', 'nome' => 'BORRACHA DO ESCAPAMENTO', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-ESC-1094', 'nome' => 'ABRAÇADEIRA ESCAPAMENTO', 'categoria' => 'escapamento'],
    ['codigo' => 'IMP-FIL-0204', 'nome' => 'FILTRO AR CONDICIONADO - ACP131 TECFIL DOBLO', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0205', 'nome' => 'FILTRO AR CONDICIONADO S10', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0206', 'nome' => 'FILTRO AR DO MOTOR - C370011 MAN DOBLO', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0207', 'nome' => 'FILTRO AR GM S10 2.4/2.8 12/', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0208', 'nome' => 'FILTRO AR MOTOR', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0209', 'nome' => 'FILTRO AR MOTOR ARL4152 - TECFIL', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0210', 'nome' => 'FILTRO AR MOTOR EAFB011 - FILTROS BRASIL', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0211', 'nome' => 'FILTRO AR MOTOR HLP4152 -VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0212', 'nome' => 'FILTRO AR MOTOR STRADA 21 HLP4152 - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0213', 'nome' => 'FILTRO AR VW - VW/11.180 DRC 4X2', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0215', 'nome' => 'FILTRO CABINE ACP906 - TECFIL', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0216', 'nome' => 'FILTRO CABINE FAC906 - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0217', 'nome' => 'FILTRO CABINE FB512 - FILTROS BRASIL', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0218', 'nome' => 'FILTRO COMB FS04/7 - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0219', 'nome' => 'FILTRO COMB FS407 - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0220', 'nome' => 'FILTRO COMB. KL582 - MAHLE', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0222', 'nome' => 'FILTRO COMBUSTIVEL - KL 582', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0223', 'nome' => 'FILTRO COMBUSTIVEL DIESEL - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0224', 'nome' => 'FILTRO COMBUSTIVEL EXPRESS VW - VW/11.180 DRC 4X2', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0225', 'nome' => 'FILTRO COMBUSTIVEL FCFB001 - FILTROS BRASIL', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0226', 'nome' => 'FILTRO COMBUSTIVEL PRIMARIO CAMINHAO - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0227', 'nome' => 'FILTRO COMBUSTIVEL S10 2.8 12/TDI', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0228', 'nome' => 'FILTRO COMBUSTIVEL SECUNDARIO CAMINHAO - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0229', 'nome' => 'FILTRO COMBUSTIVEL VW - VW/11.180 DRC 4X2', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0230', 'nome' => 'FILTRO DE AR CONDICIONADO DIESEL - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0231', 'nome' => 'FILTRO DE AR MOTOR - EAFB247 FILTROS BRASIL', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0232', 'nome' => 'FILTRO DE AR MOTOR DIESEL - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0233', 'nome' => 'FILTRO DE AR MOTOR DIESEL CAMINHAO - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0234', 'nome' => 'FILTRO DE COMBUSTIVEL - DOBLO', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0235', 'nome' => 'FILTRO DE OLEO - DOBLO', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0236', 'nome' => 'FILTRO DE OLEO DIESEL - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0237', 'nome' => 'FILTRO DE OLEO MOTOR DIESEL CAMINHAO - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0238', 'nome' => 'FILTRO LUBRIF GM WOE314 WEGA', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0239', 'nome' => 'FILTRO LUBRIFICANTE VW 8150/23250 - VW/11.180 DRC 4X2', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0241', 'nome' => 'FILTRO OLEO - S10', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0242', 'nome' => 'FILTRO OLEO FOFB005 - FILTROS BRASIL', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0243', 'nome' => 'FILTRO OLEO LB55 - VOX', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0244', 'nome' => 'FILTRO OLEO OC196 - MAHLE', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0245', 'nome' => 'FILTRO OLEO W6100 - MANN', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0311', 'nome' => 'KIT FILTRO HILLUX 2.8 2016', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0312', 'nome' => 'KIT FILTRO OLEO/AR/COMB/CAB>GM S10/BLAZ2.8 16V', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0719', 'nome' => 'FILTRO DE AR CABINE', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0742', 'nome' => 'FILTRO DE OLEO - MOBI', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0791', 'nome' => 'FILTRO CABINE MERCEDES ACCELO TODOS', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0856', 'nome' => 'FILTRO DE COMBUSTIVEL KL582 - MAHLE', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0894', 'nome' => 'FILTRO DE OLEO FIAT FIRE', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0910', 'nome' => 'FILTRO COMBUTIVEL SECUNDARIO', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0960', 'nome' => 'FILTRO DIESEL', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-0985', 'nome' => 'FILTRO COMBUSTIVEL SEPARADOR DE ÀGUA', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-2007', 'nome' => 'FILTRO DE ÓLEO - WEGA', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-2008', 'nome' => 'FILTRO COMBUSTIVEL - WEGA', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-2009', 'nome' => 'FILTRO CABINE - METAL LEVE', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FIL-2010', 'nome' => 'FILTRO AR MOTOR - METAL LEVE', 'categoria' => 'filtros'],
    ['codigo' => 'IMP-FRE-0142', 'nome' => 'CILINDRO MESTRE FREIO C/ABS STRADA 21 PMH6006 - TRW', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0174', 'nome' => 'CX DISCO TACOGRAFO DML 7 DIAS 125KM', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0187', 'nome' => 'DISCO DIAGRAMA TACOGRAFO', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0188', 'nome' => 'DISCO FREIO DIANT VENTIL', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0189', 'nome' => 'DISCO FREIO L200', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0190', 'nome' => 'DISCO FREIO MOBI HF31B - HIPPER FREIOS', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0191', 'nome' => 'DISCO FREIO STRADA 21 HF30 - HIPPER FREIOS', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0192', 'nome' => 'DISCO FREIO VENTILADOR', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0250', 'nome' => 'FLUIDO FREIO DOT 4 - 500ML', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0251', 'nome' => 'FLUIDO FREIO DOT 4 - TRW', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0252', 'nome' => 'FLUIDO FREIO DOT 4 500 ML - KOUBE', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0276', 'nome' => 'JOGO DE LONA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0277', 'nome' => 'JOGO DE PASTILHAS DE FREIO - STRADA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0278', 'nome' => 'JOGO DE SAPATA DE FREIO - STRADA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0315', 'nome' => 'KIT PASTILHA DE FREIO 9187 SYL COBRA DOBLO', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0356', 'nome' => 'LIMPA FREIO', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0373', 'nome' => 'LONA  TRACAO 815/8150', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0374', 'nome' => 'LONA FREIO - L559 STD - WW 11.180', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0375', 'nome' => 'LONA FREIO VW 10160', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0376', 'nome' => 'LONA PLASTICA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0392', 'nome' => 'MOLA PATIM FREIO TRAS B-120D/9-15D', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0393', 'nome' => 'MOLA PATIM FREIO TZ - 2258FM03 WW 11.180', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0440', 'nome' => 'PASTILHA DE FREIO', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0441', 'nome' => 'PASTILHA DE FREIO DI BB771 B0747 L200 PAJ', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0442', 'nome' => 'PASTILHA DE FREIO DIANT L200 2021 PD771 - FRASLE', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0443', 'nome' => 'PASTILHA DE FREIO STRADA 2021 CO-N540 - COBREQ', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0444', 'nome' => 'PASTILHA DE FREIO STRADA 2021 GDB9167 - TRW', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0445', 'nome' => 'PASTILHA DE FREIO STRADA 2021 PD2226 - FRASLE', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0446', 'nome' => 'PASTILHA DE FREIO SUV', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0447', 'nome' => 'PASTILHA FREIO MOBI P85 - LONAFLEX', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0496', 'nome' => 'REBITE LONA 10X14 ALUMINIO SEM TUBULAR', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0551', 'nome' => 'SAPATA DE FREIO - DOBLO 1.8 10/', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0552', 'nome' => 'SAPATA DE FREIO - FIAT NOVA STRADA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0553', 'nome' => 'SAPATA DE FREIO MOBI SA40135 - AUTHO MIX', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0554', 'nome' => 'SAPATA DE FREIO SUV', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0555', 'nome' => 'SAPATA FREIO TRAS FIAT STRADA 21 90147 - MAZZICAR', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0556', 'nome' => 'SAPATA FREIO TRAS FIAT STRADA 21 FI/432 - FRASLE', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0557', 'nome' => 'SAPATA FREIO TRAS GM CLASSIC SYL201703 - SYL', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0666', 'nome' => 'TAMBOR  FREIO', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0667', 'nome' => 'TAMBOR DE FREIO VW 10160/13160 DT/TR', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0668', 'nome' => 'TAMBOR FREIO DT - 4320 WW 11.180', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0669', 'nome' => 'TAMBOR FREIO GM CLASSIC HF 24 - HIPER FREIOS', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0670', 'nome' => 'TAMBOR FREIO MOBI HF36A - HIPPER FREIOS', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0671', 'nome' => 'TAMBOR FREIO TZ - 4323 WW 11.180', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0727', 'nome' => 'PASTILHA REGULADORA DE VALVULA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0729', 'nome' => 'TAMBOR DE FREIO TRASEIRO', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0745', 'nome' => 'PASTILHA DE FREIO DIANTEIRA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0750', 'nome' => 'PASTILHA FREIO DI BB1482 NOVO UNO PAL', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0773', 'nome' => 'PEDAL FREIO TITAN 160 ESD COMETA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0773', 'nome' => 'PASTILHA MOLA DT VW FORD', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0797', 'nome' => 'JOGO TAMBOR DE FREIO', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0815', 'nome' => 'JOGO DE SAPATA DE FREIO DE MÃO', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0816', 'nome' => 'JOGO DE PASTILHA DE FREIO TRASEIRA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0867', 'nome' => 'JOGO DE PASTILHA FREIO DIANTEIRA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0868', 'nome' => 'DISCO DE FREIO DIANTEIRO VENTILADOR', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-0956', 'nome' => 'JOGO SAPATA COM LONA TRASEIRA', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-1044', 'nome' => 'PINÇA DE FREIO L/E', 'categoria' => 'freios'],
    ['codigo' => 'IMP-FRE-2003', 'nome' => 'SAPATA FREIO TRASEIRO', 'categoria' => 'freios'],
    ['codigo' => 'IMP-GER-0002', 'nome' => 'ABRACADEIRA  NYLON 283 X 4.8MM PT', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0003', 'nome' => 'ABRAÇADEIRA CHASSIS - 22508', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0006', 'nome' => 'ABRAÇADEIRA EM AÇO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0007', 'nome' => 'ABRAÇADEIRA FITA 9MM 2C2 1/2 ZINCADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0008', 'nome' => 'ABRACADEIRA MICRO 13X19 9MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0009', 'nome' => 'ABRACADEIRA MICRO 19X27 9MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0010', 'nome' => 'ABRACADEIRA MICRO 32X44 9MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0012', 'nome' => 'ABRAÇADEIRA PLASTICA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0013', 'nome' => 'ABRACADEIRA TIPO U POL7/8', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0018', 'nome' => 'AGUA DESMINERALIZADA 1L', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0019', 'nome' => 'AGULHA DE TEMPO E VELOCIDADE 125 KM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0046', 'nome' => 'ANÉIS SINCRONIZADOS 3° E 4° ORIGINAL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0047', 'nome' => 'ANEL BACK-UP 25,86X30,55X1,35', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0048', 'nome' => 'ANEL COLUNA DIREÇÃO VW 10160', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0049', 'nome' => 'ANEL ENCOSTO 0.25', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0050', 'nome' => 'ANEL ORING 10,77X2,62', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0051', 'nome' => 'ANEL ORING 25,07X2,62', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0055', 'nome' => 'ARRUELA 06/08/10 MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0056', 'nome' => 'ARRUELA ALUMINIO VEDACAO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0057', 'nome' => 'ARTICULAÇÃO AXIAL LE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0059', 'nome' => 'BALANCA - STRADA WORKING 1.4', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0060', 'nome' => 'BALANCA FIAT STRADA 1.3/1.4 20/DT LD', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0061', 'nome' => 'BALANCA FIAT STRADA 1.3/1.4 20/DT LE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0067', 'nome' => 'BARRA OXIAL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0106', 'nome' => 'BOTAO DUPLO VIDRO ELETRICO VW', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0120', 'nome' => 'BUZINA HILLUX', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0124', 'nome' => 'CAIXA DE DIREÇÃO COMPLETA - TRW STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0125', 'nome' => 'CALCO DO MOTOR TRAS. CAIXA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0126', 'nome' => 'CALCO FIAT STRADA CB', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0127', 'nome' => 'CALCO REG FUNIL FSO4305/4505C 0,102', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0128', 'nome' => 'CALHA DE CHUVA IVECO DAILY 35S14', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0133', 'nome' => 'CANETA RETROPROJETOR (PONTA FINA)', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0134', 'nome' => 'CANO DAGUA STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0139', 'nome' => 'CHAVE SETA VW DELIVERY 05', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0148', 'nome' => 'CONDENSADOR AR CONDICIONADO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0149', 'nome' => 'CONE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0150', 'nome' => 'CONECTOR 2 VIAS VW 10160', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0163', 'nome' => 'COXIM AMORT. TRAS. STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0167', 'nome' => 'COXIM MOTOR DIANT DIREITO C/ SUPORTE - STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0168', 'nome' => 'COXIM MOTOR DIANT ESQUERDO - STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0169', 'nome' => 'COXIM MOTOR DIANT LD SANDERO MB9373 NOB', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0173', 'nome' => 'CUPILHA MANGA EIXO VW 10160', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0175', 'nome' => 'DESCARBONIZANTE 300ML', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0176', 'nome' => 'DESCARBONIZANTE BIODEGRADAVEL 300ML LOC', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0177', 'nome' => 'DESCARBONIZANTE K-90 - KOUBE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0193', 'nome' => 'ELETROVENTILADOR MOBI/STRADA 21', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0195', 'nome' => 'ENGENAGEM VIRABREQUIM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0196', 'nome' => 'EQUIPAMENTO MUNCK', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0197', 'nome' => 'ESPAGUETE FIO MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0198', 'nome' => 'EVAPORADOR - CAMINHAO ACELLO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0199', 'nome' => 'EVAPORADOR STRADA 21 - ACP', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0246', 'nome' => 'FITA 3MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0247', 'nome' => 'FITA REFLETIVA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0248', 'nome' => 'FITA TECIDO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0249', 'nome' => 'FLEXIVEL 20178 - SCAPEX COM TUBO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0254', 'nome' => 'GAXETA 19X26X5', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0255', 'nome' => 'GAXETA 25,40X34,92X4,76 - PARKER', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0256', 'nome' => 'GRADE RAD. STRADA 21/PRETA TEXT. FS13225', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0257', 'nome' => 'GRAV CHASSI ETIQUETA INFORMATIZADA VINIL 11X3CM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0258', 'nome' => 'GRAXA  MARFAK BD 0082', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0263', 'nome' => 'HIGIENIZADOR AR COND', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0303', 'nome' => 'KIT CORRENTE MOTOR HYUNDAI HR K2500 16V', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0305', 'nome' => 'KIT EMBRAGEM MB 1218E 1620 E COLAR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0314', 'nome' => 'KIT PAST GARFO FSO4305/4405/4505 FSO4305/4405/4505', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0348', 'nome' => 'LANTERNA  DIREITA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0349', 'nome' => 'LANTERNA ADAP. LED BRANCA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0350', 'nome' => 'LANTERNA LED SINALIZ LATERAL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0351', 'nome' => 'LANTERNA TRAS ATEGO 2430 - PARALELA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0370', 'nome' => 'LIXA FERRO 0.36', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0371', 'nome' => 'LIXA FERRO 150 TYROLITE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0372', 'nome' => 'LIXA FERRO 80', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0379', 'nome' => 'LUVA DE 3° E 4° ORIGINAL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0380', 'nome' => 'MACACO  JOELHO ROSCA UNIVERSAL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0381', 'nome' => 'MANCHAO MP10R 112 REPARO MULTI FURO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0382', 'nome' => 'MANG AQUECEDOR - STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0384', 'nome' => 'MANG RETORNO AGUA - STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0398', 'nome' => 'MOTOR DE PARTIDA 12 V - STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0399', 'nome' => 'MOTOR VENTILAÇÃO INTERNO AR CONDICIONADO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0426', 'nome' => 'ORING BOCA DA CAIXA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0427', 'nome' => 'PALETA IVECO DAILY 35S14', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0436', 'nome' => 'PARAFUSO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0437', 'nome' => 'PARAFUSO CABECOTE- STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0448', 'nome' => 'PINO MANGA EIXO VW DELIVERY 8160/9160 33,10MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0451', 'nome' => 'PIVO - STRADA ENDURANCE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0452', 'nome' => 'PIVO - STRADA WORKING 1.4', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0454', 'nome' => 'PIVO STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0484', 'nome' => 'PORCA CROMADA ONIX GM UNIPAR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0485', 'nome' => 'PORCA DE 06/08/10 MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0488', 'nome' => 'PRESILHA DO FORRO TAMPA TRASEIRA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0489', 'nome' => 'PRODUTO LIMPEZA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0490', 'nome' => 'QUEROSENE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0493', 'nome' => 'RASPADOR 19,05X28,57X4,76 - PARKER', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0494', 'nome' => 'REBITE  10X16 ALUMINIO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0495', 'nome' => 'REBITE 10X10 ALUMINIO MACICO - RBB', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0528', 'nome' => 'RESERVATORIO DE AGUA - G1319 GONEL DPK DOBLO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0530', 'nome' => 'RESERVATÓRIO EXPANSÃO FIAT STRADA 21', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0558', 'nome' => 'SAPATA TRAS 2700-CP - COBREQ', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0579', 'nome' => 'SILICONE ALTA TEMPERATURA TEMP DIRKO ~60 C+3', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0580', 'nome' => 'SILICONE NEUTRO BLACKSUL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0581', 'nome' => 'SILICONE P/ MOTOR PRETO 329G 70GR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0582', 'nome' => 'SIRENE REBLINDADA 12 24V RESIST AGUA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0584', 'nome' => 'SONDA LAMBDA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0585', 'nome' => 'SONDA LAMBDA GM CELTA -', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0589', 'nome' => 'SOQUETE LANTERNA VW 10160', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0590', 'nome' => 'SPRAY PRETO ALTA TEMPERATURA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0662', 'nome' => 'SUPORTE DE CELULAR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0672', 'nome' => 'TAMPA ARLA VW 10160', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0673', 'nome' => 'TAMPA RESERVATORIO DE AGUA DOBLO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0674', 'nome' => 'TAMPA RESERVATÓRIO DE ÁGUA STRADA 21', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0677', 'nome' => 'TECHBOND', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0678', 'nome' => 'TEE UNIAO 3/8 MONTADO 1009038/CCA12-060M/MDM-190 MA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0685', 'nome' => 'THINNER COMUM 900ML CO100', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0686', 'nome' => 'THINNER COMUM 900ML ITAQUA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0687', 'nome' => 'TRANCA DA TAMPA TRASEIRA STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0693', 'nome' => 'TUBO DE COLA BLACK 598', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0694', 'nome' => 'TUBO INTERMEDIÁRIO DESCARGA FLEXIVEL STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0695', 'nome' => 'TUBO LIGAÇÃO BBA DAGUA OM904 OM 90', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0696', 'nome' => 'TUBO REFRIG MOTOR - STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0697', 'nome' => 'VALV SOLEN BUZINA AR 24V', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0703', 'nome' => 'VÁLVULA TERMOSTÁTICA STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0712', 'nome' => 'VIDRO PARABRISA ACCELO 1017', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0713', 'nome' => 'VIDRO PARABRISA STRADA PB 21/CD/CS VSF (MI/P/SER/SP/SPP) PK', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0716', 'nome' => 'VOLANTE MOTOR S10', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0720', 'nome' => 'BUZINA - GOL PARATI SAVEIRO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0720', 'nome' => 'ARTICULAÇÃO AXIAL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0721', 'nome' => 'PLACA RETIF WASPA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0722', 'nome' => 'ANEL BUJÃO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0722', 'nome' => 'REGULADOR ALT BOSCH HILUX 2015>14V 90A', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0723', 'nome' => 'ROL FIXO ESFERAS', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0734', 'nome' => 'COTOVELO MACHO ORING 3/4X3/4', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0736', 'nome' => 'SILENCIADOR TRASEIRO - CELTA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0737', 'nome' => 'GUARNIÇÃO VID VIGIA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0737', 'nome' => 'REFIL VIPASEAL AUTO 100MM VIPAL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0739', 'nome' => 'VID PB AUTOMOTIVO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0739', 'nome' => 'CALÇO DE SAPATA - CAMINHÃO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0741', 'nome' => 'BORRACHA DE VEDAÇÃO L/E - STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0742', 'nome' => 'BORRACHA DE VEDAÇÃO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0743', 'nome' => 'KIT FRISO TETO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0744', 'nome' => 'SIRENE RE COMPACTA C/REDUTOR SOM 12/24V', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0744', 'nome' => 'TOP KIT TRASEIRO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0746', 'nome' => 'ABRAÇADEIRA NYLON 40MMX 4.8MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0746', 'nome' => 'LANTERNA TRASEIRA LD', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0747', 'nome' => 'CABO 1,5 MM AUTO FLEXIVEL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0750', 'nome' => 'GALÃO 5L', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0753', 'nome' => 'ESCAP. INTERMEDIARIO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0754', 'nome' => 'ESCAP. TRASEIRO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0755', 'nome' => 'ESCAP. FLEXIVEL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0755', 'nome' => 'CINTA DE 5 TON. (5,6)', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0758', 'nome' => 'ABRAÇADEIRA ROSCA S/FIM 16A22', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0759', 'nome' => 'VEDA SCAP - 100MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0759', 'nome' => 'VOLANTE DE CELTA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0760', 'nome' => 'ABRAÇADEIRA ESCAP 100MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0761', 'nome' => 'CONTRA PINO - MB', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0762', 'nome' => 'PINO CENTRO 10X7', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0763', 'nome' => 'PORCA 10 MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0764', 'nome' => 'ABRAÇADEIRA CHAPA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0765', 'nome' => 'REBITE 3/8', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0766', 'nome' => 'TUBO FLEXIVEL GM CORSA CELTA 10 8V', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0766', 'nome' => 'PARAFUSO 3/8X4', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0768', 'nome' => 'GRAMPO 9/16X82X280', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0769', 'nome' => 'INTERRUPTOR LIG/DES TIPO TIC TAC', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0769', 'nome' => 'PORCA 9/16 DT', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0772', 'nome' => 'TAMPA LATERAL FAN 160 CARGO PRETO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0774', 'nome' => 'PROTETOR ESCAPE TITAN 160 QUALLY', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0774', 'nome' => 'REBITE FERRO CABEÇA REDONDA 3/8X1', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0775', 'nome' => 'ADESIVO COMPLETO TITAN 150.160', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0775', 'nome' => 'GRAMPO 9/16X72X200 D DT 709', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0776', 'nome' => 'GRAMPO 9/16X72X180 D DT 709', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0777', 'nome' => 'PORCA 9/16 UNF DUPLA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0779', 'nome' => 'MANOPLA VIO WESTER ALUMINIUM CORES WESTER', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0779', 'nome' => 'LAMAPDA 1141 AMBAR 1 POLO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0780', 'nome' => 'CABO 7x1 PARA INSTALAÇÃO AUTOMOTIVA FIO COBRE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0781', 'nome' => 'ABRAÇADEIRA NYLON  40MMX 4.8MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0781', 'nome' => 'COXIM MOTOR DIANTEIRO DIRE ITO C/SUPORTE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0782', 'nome' => 'COXIM MOTOR DIANTEIRO LE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0782', 'nome' => 'LENTE LANT TRAS TRICOLOR REFORÇADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0782', 'nome' => 'KIT ALAVANCA COM CABO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0784', 'nome' => 'ESPAGUETE CORRUGADO ANTI-CHAMAS 4.50MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0784', 'nome' => 'CABO DE IGNICÃO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0785', 'nome' => 'CABO 1.5 MM AUTO FLEXIVEL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0786', 'nome' => 'FITA ISOLANTE COM COLA 10 MTS', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0788', 'nome' => 'PILHA BOTÃO DE LÍTIO MODL 2032 3V', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0789', 'nome' => 'EVAPORADOR MB ACCELO NEW HOLLAND', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0789', 'nome' => 'ELETROVENTILADOR 12V 10 POL.', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0790', 'nome' => 'NUCLEO DE VALV R134 VENTIL', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0790', 'nome' => 'CAPÔ ( SEM PINTURA )', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0791', 'nome' => 'GRADE FRONTAL ( COM LOGO )', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0792', 'nome' => 'KIT COM DUAS CANALETAS (D/E)', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0794', 'nome' => 'BALDE 20 L 80 - HEXLUB', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0794', 'nome' => 'CALÇO (SUPORTE) SUPERIOR DO MOTOR LD', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0794', 'nome' => 'ANTICHAMAS', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0795', 'nome' => 'CALÇO (SUPORTE) SUPERIOR DO MOTOR LE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0796', 'nome' => 'GASOLINA COMUM 41L', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0797', 'nome' => 'COXIM MOTOR DIANTEIRO LD', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0798', 'nome' => 'SATELITE DA CAIXA FI 002', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0799', 'nome' => 'TRAVA DO PINO DA SATELITE FI 003', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0800', 'nome' => 'LUVA DE 5 MARCHA FI 006', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0802', 'nome' => 'PINO SATELITE FI 001', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0803', 'nome' => 'LENTE TRAZ MB', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0803', 'nome' => 'SELETORA DE MARCHAS FI 001', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0804', 'nome' => 'ANEL SINCRONIZADO DE 3 & 4 FI 004', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0805', 'nome' => 'SIRENE RE BI VTS', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0805', 'nome' => 'LUVA DA 3 & 4 MARCHA FI 002', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0806', 'nome' => 'CONJUNTO DE ENGRENAGEM DE 5 MARCHA FI 005', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0807', 'nome' => 'ABRAÇADEIRA N 50 REFORÇADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0808', 'nome' => 'TP ARLA MB FORD CAMINHOES EUROS C/CHA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0811', 'nome' => 'SONDA LAMBDA FIAT MOBI 10 POS', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0813', 'nome' => 'RET MANGOTE AR COND P/ REPARO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0814', 'nome' => 'MACACO JACARÉ', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0816', 'nome' => 'CALÇO CX INFERIOR ( RAQUETE )', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0817', 'nome' => 'SILICONE PRETO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0818', 'nome' => 'ELEMENTOS FILTRANTE 140L - HHK01885', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0818', 'nome' => 'ABRAÇADEIRA NYLON 395MM 47031A LARGA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0823', 'nome' => 'MANOMETRO D42 ROSCA POSTERIOR 18 NPT', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0826', 'nome' => 'CAPA 1 E 2 TRAMAS SEM DESCASQUE 5/16', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0831', 'nome' => 'CAPA 1 E 2 TRAMAS SEM DESCASQUE 1/2', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0832', 'nome' => 'BORRACHA PERFIL COXIM TUBO 16MM P/CILINDRO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0833', 'nome' => 'ABRAÇADEIRA INOX FITA REGULAVEL 60-160MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0835', 'nome' => 'ABRAÇADEIRA NYLON 390MM X 7.6MM PRETA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0837', 'nome' => 'MANILHA RETA 6.5 TON ( C.G6 P. G8 FS.6:1 )', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0841', 'nome' => 'SPRAY DE COBRE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0843', 'nome' => 'VÁLVULA TERMOSTÁTICA - MOBI', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0845', 'nome' => 'PISTO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0851', 'nome' => 'ABRAÇADEIRA EM AÇO 32X44', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0852', 'nome' => 'ABRAÇADEIRA EM AÇO 12X16', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0857', 'nome' => 'ABRAÇADEIRA PLÁSTICO P, M', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0858', 'nome' => 'ABRAÇADEIRA PLÁSTICO G', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0861', 'nome' => 'TRANSDUTOR PRESSÃO GEFRAN', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0863', 'nome' => 'KIT - 6193015000', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0871', 'nome' => 'TUBO INTERMEDIARIO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0879', 'nome' => 'CONDESADOR MAHLE GOL G3 / G4', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0880', 'nome' => 'ORG TIPO MCH. TDS', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0882', 'nome' => 'GÁS R134', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0883', 'nome' => 'ABRAC. MET. 19 38X14', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0886', 'nome' => 'MANG. PARA AR CONDICIONADO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0888', 'nome' => 'GÁS REFRIGERANTE - 134A 13,6KG', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0889', 'nome' => 'ABRAC. MET.19 38X14', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0891', 'nome' => 'RESISTÊNCIA ELETROVENTILADOR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0892', 'nome' => 'SILICONE DIRKO PRETA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0893', 'nome' => 'TUBO DO FLUXO D.ÁGUA DO MOTOR UNO/FIORINO/PALIO/SIENA/STRADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0895', 'nome' => 'BICO PALIO SIENA - STRADA 14 FLEX', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0903', 'nome' => 'CALÇO DIANTEIRO SUP', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0904', 'nome' => 'CALÇO DIANTERIO INF', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0905', 'nome' => 'CALÇO TRASEIRO CABINE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0906', 'nome' => 'PARAFUSO CALÇO TRASEIRO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0915', 'nome' => 'COXIM INFERIOR SUSPENSÃO CABINE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0916', 'nome' => 'COXIM SUPERIOR SUSPENSÃO CABINE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0917', 'nome' => 'COXIM TRASEIRO CABINE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0918', 'nome' => 'COXIM DIANTEIRO SUSPENSÃO CABINE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0919', 'nome' => 'ABRAÇADEIRA PLASTICA 4.80MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0926', 'nome' => 'ABRAÇADEIRA ZINCADA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0932', 'nome' => 'GRAXEIRA RETA 3/8 UNF 24F', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0933', 'nome' => 'TRAVA GANCHO GIRATORIO 7,5 TONS', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0934', 'nome' => 'ECONOLINE HIDRAULICO 68 20L', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0941', 'nome' => 'CONEXÃO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0943', 'nome' => 'KIT AR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0949', 'nome' => 'JOGO DE ANEL CINCRONIZADO 2° MARCHA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0950', 'nome' => 'SILICONE DE ALTA TEMPERETURA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0964', 'nome' => 'THINNER ECOLOGICO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0967', 'nome' => 'BOTÃO SIMPLES INTERRUPTOR VIDRO CO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0968', 'nome' => 'BOTÃO ACIONAR VIDRO INTERRUPTOR V', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0969', 'nome' => 'KIT REPARO DO COMANDO HIDRAULICO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0974', 'nome' => 'CABO DE IGNIÇÃO BOSCH', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0979', 'nome' => 'SEMI-EIXO COMPLETO L/E (MOTORISTA)', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0983', 'nome' => 'PORCA 5/8 UNC SIMPLES', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0993', 'nome' => 'TRIZETA IMA-624-Bip LE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0998', 'nome' => 'KIT DE REPARO DO TRAMBULADOR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-0999', 'nome' => 'CABO DE MARCHA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1012', 'nome' => 'ANTI FERRUGEM BLACK', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1018', 'nome' => 'ALMA PARA-CHOQUE TRASEIRO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1020', 'nome' => 'ALAVANCA ARTICULADA ENGATE CORSA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1021', 'nome' => 'TERMINEL CABO COMANDO CORSA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1023', 'nome' => 'REPARO TERM. CABO ENGUINIÇÃO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1026', 'nome' => 'FIO 2MT', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1031', 'nome' => 'FITA TEC. ALGODÃO IMPERM 19MM X', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1032', 'nome' => 'ABRAÇADEIRA NYLON 400 X 7,5 PT', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1039', 'nome' => 'PINO ELO 1/4', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1040', 'nome' => 'PINO DE LANÇA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1041', 'nome' => 'TRAVA DE GANCHO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1049', 'nome' => 'COMPRESSOR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1050', 'nome' => 'CONDENSADOR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1051', 'nome' => 'NITROGENIO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1057', 'nome' => 'FIO COBRE 1,5 E 2,5', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1058', 'nome' => 'MANG HIDR 100R-6 SAPATA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1060', 'nome' => 'CABO FLEXIVEL PP 4X1.00MM 25M', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1061', 'nome' => 'ESPAGUETE CORRUGADO (3/8) 9.50MM', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1065', 'nome' => 'ABRAÇADEIRA NYLON PT EKABR7023', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1068', 'nome' => 'CABO DE AÇO TAMPA TRASEIRA (PAR)', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1069', 'nome' => 'SUPORTE PISANTE DA CARROCERIA LD VW', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1071', 'nome' => 'ORG/ TRM.EN.S/TRAV', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1072', 'nome' => 'ABRAÇADEIRA NYLON PRETA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1075', 'nome' => 'KIT DE DISTRUBUIÇÃO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1079', 'nome' => 'CALÇO MOTOR LD', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1081', 'nome' => 'LANTERNA TRASEIRA STRADA LD', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1090', 'nome' => 'LANTERNA TRASEIRA LE', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1095', 'nome' => 'RELÊ BUZINA', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1096', 'nome' => 'SUPORTE PARA CARROCERIA - SANTO ANTONIO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1098', 'nome' => 'CILINDRO MESTRE - HR 2013', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-2001', 'nome' => 'ANEL DE VEDAÇÃO DIN', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-2013', 'nome' => 'PORCA 8MM MA 1.25 ZB CH13', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-2014', 'nome' => 'PORCA C/ PARAFUSO', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1123', 'nome' => 'EVAPORADOR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-GER-1124', 'nome' => 'SELO COMPRESSOR', 'categoria' => 'geral'],
    ['codigo' => 'IMP-MOT-0084', 'nome' => 'BICO DE VALVULA R414/R418', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0085', 'nome' => 'BIELA MOTOR HR 2.5 16V', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0096', 'nome' => 'BOBINA DE IGNIÇÃO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0097', 'nome' => 'BOBINA TACOGRAFO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0098', 'nome' => 'BOMBA D`ÁGUA STRADA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0099', 'nome' => 'BOMBA DAGUA HR HYUNDAI 2.5 16V', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0100', 'nome' => 'BOMBA DAGUA MOBI 2021 7000354009 - ÍNDISA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0101', 'nome' => 'BOMBA DE COMBUSTIVEL COMPLETA - S10', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0102', 'nome' => 'BOMBA DE COMBUSTÍVEL RENAULT SANDERO - WEBER', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0103', 'nome' => 'BOMBA ELETRICA LIMPADOR PARABRISA 12V', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0121', 'nome' => 'CABO DE VELA GM CELTA SC-G73 - NGK', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0122', 'nome' => 'CABO DE VELA STRADA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0155', 'nome' => 'CORREIA ALT MB AXOR 8PK 1940', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0156', 'nome' => 'CORREIA ALTERNADOR', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0157', 'nome' => 'CORREIA AR CONDICIONADO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0158', 'nome' => 'CORREIA DE ACESSORIOS 6PK1390 - DOBLO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0159', 'nome' => 'CORREIA DENTADA MOBI CT488 - CONTINENTAL', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0160', 'nome' => 'CORREIA MICRO V ELAST 3PK0895SP - GATES', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0161', 'nome' => 'CORREIA POLY V 5PK1175 - GATES', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0162', 'nome' => 'CORREIA POLY V 6PK1288 - GATES', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0274', 'nome' => 'JOGO DE CABO DE VELA IGNICAO FIATFIRE FLEX 8V', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0275', 'nome' => 'JOGO DE CABO DE VELA STRADA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0279', 'nome' => 'JOGO DE VELA FIAT UNO-PALIO FLEX 8V', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0280', 'nome' => 'JOGO DE VELA STRADA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0281', 'nome' => 'JOGO JUNTA COMPLETA MOTOR HR 2.5 16V', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0282', 'nome' => 'JOGO JUNTA MOTOR SUPERIOR - STRADA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0283', 'nome' => 'JUNTA COLETOR ESCAP STRADA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0284', 'nome' => 'JUNTA DA TAMPA DA VALVULA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0285', 'nome' => 'JUNTA DO COLETOR DE ESCAP STRADA 2021 - CORTECO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0286', 'nome' => 'JUNTA DO ESCAPE MOBI', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0287', 'nome' => 'JUNTA DO FLEXIVEL/CATALIZADOR STRADA 2021 - DIVICAR', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0288', 'nome' => 'JUNTA HOMOCINÉTICA GM CLASSIC - COFAP', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0289', 'nome' => 'JUNTA HOMOCINÉTICA LADO RODA STRADA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0290', 'nome' => 'JUNTA HOMOCINÉTICA RODA LD/LE STRADA 21/22', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0291', 'nome' => 'JUNTA SUPERIOR VALVULA TERMOSTATIC', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0292', 'nome' => 'JUNTA TAMPA DE VÁLVULA STRADA 2021 75305 - SABÓ', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0293', 'nome' => 'JUNTA TAMPA VALVULA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0294', 'nome' => 'JUNTA TAMPA VALVULA GM CELTA - 598-190 - ELRING', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0302', 'nome' => 'KIT CORREIA DENTADA E TENSIONAR KS-210 - GATES', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0532', 'nome' => 'RETENTOR CAMBIO FUNIL FSO4305 07021BR', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0533', 'nome' => 'RETENTOR CAMBIO TR FS4305/4405/45054405/4505', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0534', 'nome' => 'RETENTOR COMANDO VALVULA - STRADA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0535', 'nome' => 'RETENTOR RODA VW', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0547', 'nome' => 'ROLAMENTO 6203 ALT BOMBA INJET EIXO PILOTO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0548', 'nome' => 'ROLAMENTO POLIA TENSORA 6304 WRSHC3 MB 0370 - 6304DDU', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0663', 'nome' => 'SUPORTE HASTE TENSOR DIR GM MONTANA - MG MANGUEIRA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0664', 'nome' => 'SUPORTE HASTE TENSOR ESQ GM MONTANA - MG MANGUEIRA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0675', 'nome' => 'TAMPA VALVULAS STRADA 2021 - ORIGINAL FIAT', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0676', 'nome' => 'TAMPAO COMANDO VALVULA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0679', 'nome' => 'TENSOR CORREIA DENTADA MOBI T357704 - ÍNDISA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0680', 'nome' => 'TENSOR DA CORREIA DO ALTERNADOR - STRADA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0698', 'nome' => 'VALVULA PARA SENSORES RODA JEDAL', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0699', 'nome' => 'VALVULA PISTO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0700', 'nome' => 'VALVULA PNEU S/CAMARA 414', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0701', 'nome' => 'VALVULA SERVIÇO  - AR COND.', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0702', 'nome' => 'VALVULA TERMOSTÁTICA MOBI VC442288 - VALCLEI', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0705', 'nome' => 'VEDA JUNTAS PT 3M 75GR', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0706', 'nome' => 'VELA GM CELTA BR8ES-D - NGK', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0707', 'nome' => 'VELA IGNIÇÃO STRADA 21', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0721', 'nome' => 'BOMBA DO HIDRÁULICO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0725', 'nome' => 'RETENTOR HASTE DE VALVULA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0726', 'nome' => 'RETENTOR DO EIXO COMANDO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0728', 'nome' => 'GUIA DE VALVULA FIRE 1.4 ST', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0729', 'nome' => 'VALVULA DE ADMISSAO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0735', 'nome' => 'BOMBA HIDRAULICA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0738', 'nome' => 'JUNTA INFERIOR CATALISADOR', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0740', 'nome' => 'JUNTA SUPERIOR CATALISADOR', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0747', 'nome' => 'BOMBA DE ALTA (REMANUFATURADO)', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0748', 'nome' => 'BOMBA DE BAIXA PRESSÃO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0756', 'nome' => 'TAMPA DE VALVULA DO CABEÇOTE', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0757', 'nome' => 'MANGUEIRA LIG. BOMBA VACUO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0762', 'nome' => 'RETENTOR CUBO DIANT', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0768', 'nome' => 'JUNTA MOTOR FIAT EVO 1.4', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0785', 'nome' => 'RETENTOR DO EIXO PILOTO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0788', 'nome' => 'VALVULA TORRE', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0809', 'nome' => 'TENSOR CORREIA DISTRIB PALIO SIE STD 14', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0810', 'nome' => 'CORREIA DIST FIAT PALIO OUNTO 13 14 8V', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0814', 'nome' => 'ESTICADOR DE CORREIA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0820', 'nome' => 'TENSOR CORREIA DENTADA  - STRADA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0836', 'nome' => 'VALVULA HIDR RETENÇÃO PILOTADA DUPLA PASSAGEM 45L', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0840', 'nome' => 'KIT JUNTA SUPERIOR DO CABEÇOTE DE AÇO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0842', 'nome' => 'JUNTA TAMPA DE VÁLVULA - TAMPA DE PLÁSTICO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0848', 'nome' => 'JOGO DE PARAFUSO CABEÇOTE', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0849', 'nome' => 'KIT VELAS', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0850', 'nome' => 'KIT VELAS - KR8B (NGK)', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0859', 'nome' => 'TAMPA DA BOMBA DE COMBUSTÍVEL E VEDAÇÃO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0873', 'nome' => 'JUNTA DO CATALISADOR INFERIOR', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0875', 'nome' => 'CORREIA DE DIREÇÃO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0876', 'nome' => 'JUNTA DA TAMPA DE VALVULA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0877', 'nome' => 'CORREIA DO ALTERNADOR', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-0925', 'nome' => 'PROTEÇÃO DA CORREIA DENTADA SUP.', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1000', 'nome' => 'BOMBA EMBREAGEM DO PEDAL (CLIND. PEDAL )', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1001', 'nome' => 'BOMBA EMBREAGEM ATUADOR ( CLIND. ATUADOR )', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1003', 'nome' => 'CORREIA DO HIDRAULICO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1024', 'nome' => 'RETENTOR SELETORA C MANC', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1028', 'nome' => 'SUBST VALVULA DE VEDAÇÃO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1036', 'nome' => 'SUPORTE TENSOR ( MORCEGO )', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1045', 'nome' => 'CORREIA DE ACESSORIO POLY V', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1046', 'nome' => 'CORREIA DE ACESSORIOS MICRO V', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1074', 'nome' => 'CORREIA COMANDO', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1085', 'nome' => 'BOBINA 2 TORRES 3 PINOS', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-1097', 'nome' => 'ROLAMENTO RODA DIANTEIRA - HR 2013 (KIT C/ RETENTOR)', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-2002', 'nome' => 'JUNTA DA TAMPA DO CABEÇOTE', 'categoria' => 'motor'],
    ['codigo' => 'IMP-MOT-2005', 'nome' => 'POLIA BOMBA HIDRAULICA', 'categoria' => 'motor'],
    ['codigo' => 'IMP-OLE-0015', 'nome' => 'ADITIVO RADIADOR ROSA 1L', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0016', 'nome' => 'ADITIVO RADIADOR ROSA 1L - TECBRIL', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0104', 'nome' => 'BOMBA OLEO HYUNDAI HR 2.5 16V', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0400', 'nome' => 'OLEO 5W30 LUBRAX', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0401', 'nome' => 'OLEO 68 1LT HIDRAMAX AW HIDRAULICO', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0402', 'nome' => 'OLEO 80W90 CX24L EATON AZUL', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0403', 'nome' => 'OLEO ATF MINERAL / GM DEXRON lll-H / TRANS AUT DIRECAO', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0404', 'nome' => 'OLEO CAMBIO - TUTELA ZC 80', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0405', 'nome' => 'OLEO CAMBIO 75W90 TUTELA 1L - S10', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0406', 'nome' => 'OLEO CAMBIO 80W90 - LUBRAX', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0407', 'nome' => 'OLEO CAMBIO 85W140 GL5 LUBRAX - S10', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0408', 'nome' => 'OLEO DE CAIXA 75W40', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0409', 'nome' => 'ÓLEO DE CAIXA 75W80', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0410', 'nome' => 'OLEO DE CAIXA SAE90 - PETRONAS', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0411', 'nome' => 'OLEO DE MOTOR 5W30 X-TECH CLEAN MOTUL', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0412', 'nome' => 'OLEO DIREÇÃO HIDRÁULICA ATF', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0413', 'nome' => 'OLEO LUBRAX TOP TURBO 20LTS', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0414', 'nome' => 'OLEO LUBRIFICANTE AUTOM', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0415', 'nome' => 'OLEO MOTOR 5W30 - IPIRANGA', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0416', 'nome' => 'OLEO MOTOR 5W30 - MOBIL', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0417', 'nome' => 'OLEO MOTOR 5W30 - SELENIA', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0418', 'nome' => 'OLEO MOTOR 5W30 - TEXACO HAVOLINE', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0419', 'nome' => 'OLEO MOTOR 5W30 DIESEL - LUBRAX', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0420', 'nome' => 'OLEO MOTOR 5W30 LUBRAX VALORA OFFROAD 1L', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0421', 'nome' => 'OLEO MOTOR 5W30 SP OFF - LUBRAX', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0422', 'nome' => 'OLEO MOTOR 5W30 SP VALORA - LUBRAX', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0423', 'nome' => 'OLEO PARA CAIXA DE MARCHA', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0424', 'nome' => 'OLEO TRANSMISSAO 80 - STRADA', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0425', 'nome' => 'OLEO TURBO15W40 LUBRAX', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0491', 'nome' => 'RADIADOR DE OLEO HR 2.5 16V', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0531', 'nome' => 'RETENTOR BOMBA DE ÓLEO', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0560', 'nome' => 'SENSOR PRESSÃO ÓLEO', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0704', 'nome' => 'VARETA DE OLEO - STRADA', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0724', 'nome' => 'OLEO 75W80', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0738', 'nome' => 'RECARGA DE GÁS/ÓLEO/CONTRASTE', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0793', 'nome' => 'MANGUEIRA SUSPIRO DO OLEO', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0801', 'nome' => 'OLEO DE CAMBIO 80W90 GL5 LUBRAX', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0846', 'nome' => 'ADITIVO PARAFLU CONCENTRADO', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0854', 'nome' => 'ÓLEO DE CAIXA DE MARCHA 75w80', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0881', 'nome' => 'ÓLEO COMPRESSOR', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0887', 'nome' => 'ÓLEO COMP AR CONDICIONADO', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0994', 'nome' => 'OLEO DA CAIXA DE MARCHA 75w80', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-0996', 'nome' => 'OLEO 5W40', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-1002', 'nome' => 'OLEO TRANSMISSÃO MANUAL 75W80', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-1073', 'nome' => 'OLEO PARA TRANSMISSÃO 75W90', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-1084', 'nome' => 'OLEO 15W40 LOMG LIFE 1L', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-2004', 'nome' => 'OLEO DE EMBREAGEM', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-2006', 'nome' => 'MANGUEIRA DE ÓLEO/GRAXA 3/4', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-OLE-1122', 'nome' => 'VARETA NIVEL DE OLEO', 'categoria' => 'oleos'],
    ['codigo' => 'IMP-PNE-0143', 'nome' => 'CILINDRO RODA C3557 C/ABS CONTROIL', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0144', 'nome' => 'CILINDRO RODA GM CLASSIC RCCR01305 - TRW', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0172', 'nome' => 'CUBO DE RODA DIANT MOBI 2021 AL 630 - IMA', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0438', 'nome' => 'PARAFUSO RODA HILUX M12X44', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0457', 'nome' => 'PNEU 175/65R14  VT MAX - SPEEDMAX', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0458', 'nome' => 'PNEU 175/65R14 81H RE MAX ITR', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0459', 'nome' => 'PNEU 175/65R14 BRAVURIS - BARUM', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0460', 'nome' => 'PNEU 175/65R14 CONTINETAL ULTRA CONTACT', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0461', 'nome' => 'PNEU 175/65R14 MH01 ITR XL', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0462', 'nome' => 'PNEU 175/65R14 RE MAX - ITARO', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0463', 'nome' => 'PNEU 175/65R14 VT MAX - SPEEDMAX', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0464', 'nome' => 'PNEU 175/70R14 MH01 - SPEEDMAX', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0465', 'nome' => 'PNEU 195/65R15  - DUNLOP FM800', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0466', 'nome' => 'PNEU 195/65R15 - HIFLY', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0467', 'nome' => 'PNEU 195/65R15 - HIFLY HF261', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0468', 'nome' => 'PNEU 195/65R15 - HIFLY HH301', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0469', 'nome' => 'PNEU 195/65R15 91H FM601 FMX', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0470', 'nome' => 'PNEU 195/65R15 CONTINENTAL ULTRA CONTACT', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0471', 'nome' => 'PNEU 195/65R15 FRD16 - FARROUD', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0472', 'nome' => 'PNEU 225/75R16C FRD96 - FARROUD', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0473', 'nome' => 'PNEU 225/75R16LT 115/112Q FRD86', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0474', 'nome' => 'PNEU 235/75R17.5 143/141K SPM01 SP, 18L', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0475', 'nome' => 'PNEU 245/70 R16 - ONIX NY HT187', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0476', 'nome' => 'PNEU 245/70R16 111T IT101 ITR XL', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0477', 'nome' => 'PNEU 265/65R17 112S H-MHT01 ITR', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0478', 'nome' => 'PNEU 265/65R17 HR805 - SPEEDMAX', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0479', 'nome' => 'PNEU 265/70R16 112T IT101 ITR', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0480', 'nome' => 'PNEU 265/70R16 AT601 VIGOROUS - HIFLY', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0481', 'nome' => 'PNEU RADIAL 235/75R17.5 - XBRI LISO', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0482', 'nome' => 'PNEU REFORMADO 235/75R17.5 BRLT2 PIRELLI', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0483', 'nome' => 'PNEU TRIANGLE 225/75R16C 10PR 118/116Q TR652', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0486', 'nome' => 'PORCA RODA TOYOTA HILLUX', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0544', 'nome' => 'RODA DE FERRO ARO 15 - STRADA', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0751', 'nome' => 'CALÇO DE RODA', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0783', 'nome' => 'PNEU 195/65R15 FRD16 - SPEED MAX', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0799', 'nome' => 'PARAFUSO DE RODA TRASEIRO - LE', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0815', 'nome' => 'CHAVE DE RODA CRUZ UNIVERSAL', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0911', 'nome' => 'ESTOJO RODA TRAZEIRA VW', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0912', 'nome' => 'PORCA RODA ANEL OSCILANTE CHAVE 27 - VW', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0965', 'nome' => 'PARAFUSO RODA TRAS VW 11180', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-0966', 'nome' => 'PORCA RODA 7.90S', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-PNE-1091', 'nome' => 'PNEU 195/65R15 FRD16 - SPEEDMAX', 'categoria' => 'pneus'],
    ['codigo' => 'IMP-SUS-0004', 'nome' => 'ABRAÇADEIRA COIFA DE CAIXA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0011', 'nome' => 'ABRACADEIRA PARA COIFA DA CAIXA DE MARCHA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0014', 'nome' => 'ABRAÇADEIRAS P/ COIFA DO SEMI EIXO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0028', 'nome' => 'AMORTEC DIANT', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0029', 'nome' => 'AMORTEC DIANT DIR', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0030', 'nome' => 'AMORTEC DIANT DIR MOBI 2021 749080SP - MONROE', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0031', 'nome' => 'AMORTEC DIANT DIR STRADA 2021 - PERFECT', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0032', 'nome' => 'AMORTEC DIANT ESQ', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0033', 'nome' => 'AMORTEC DIANT ESQ MOBI 2021 749081SP - MONROE', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0034', 'nome' => 'AMORTEC DIANT ESQ STRADA 2021 - PERFECT', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0035', 'nome' => 'AMORTEC DIANT GM S10', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0036', 'nome' => 'AMORTEC DIANT MOBI 2021 DIR HG33101 - NAKATA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0037', 'nome' => 'AMORTEC DIANT MOBI 2021 ESQ HG33102 - NAKATA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0038', 'nome' => 'AMORTEC DIANT STRADA 2021 - MONROE', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0039', 'nome' => 'AMORTEC TRAS - GL 13776', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0040', 'nome' => 'AMORTEC TRAS GM MONTANA - PERFECT', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0041', 'nome' => 'AMORTEC TRAS L200 TRITON 21 343251 - KYB', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0042', 'nome' => 'AMORTEC TRAS STRADA 2021 - MONROE', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0044', 'nome' => 'AMORTECEDOR TRASEIRO SP379525SP - MONROE AXIOS DOBLO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0045', 'nome' => 'AMORTECEDOR TRASEIRO STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0062', 'nome' => 'BALANÇA L/D', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0065', 'nome' => 'BARRA AXIAL - STRADA DIDRAULICA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0066', 'nome' => 'BARRA AXIAL LADO ESQUERDO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0068', 'nome' => 'BATENTE - STRADA WORKING 1.4', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0069', 'nome' => 'BATENTE AMORTEC', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0070', 'nome' => 'BATENTE AMORTEC TRAS STRADA 2021 - SAMPEL', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0071', 'nome' => 'BATENTE AMORTECEDOR TRASIERO BATENTE 2 LADOS - STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0072', 'nome' => 'BATENTE CARROCERIA STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0073', 'nome' => 'BATENTE SUSP TRAS GM MONTANA - DIVICAR', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0074', 'nome' => 'BATENTE SUSPENSAO TRASEIRO STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0075', 'nome' => 'BATENTE TRAS  STRADA 2021 - GARRAFIX', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0086', 'nome' => 'BIELETA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0087', 'nome' => 'BIELETA DIANTEIRA STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0088', 'nome' => 'BIELETA FIAT STILO 03/PUNTO D/E DT', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0089', 'nome' => 'BIELETA GM S10 -', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0090', 'nome' => 'BIELETA MOBI 2021 - BPPROAUTO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0091', 'nome' => 'BIELETA MOBI 2021 N6081 - NAKATA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0092', 'nome' => 'BIELETA STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0093', 'nome' => 'BIELETA STRADA 2021 JTSB0006 - TRW', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0094', 'nome' => 'BIELETA STRADA 2021 VKDS6038 - SKF', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0095', 'nome' => 'BIELETAS', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0105', 'nome' => 'BORRACHA AMORTEC TRAS GM S10', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0107', 'nome' => 'BUCHA BALANÇA DIANT - PARTE DIANTEIRA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0108', 'nome' => 'BUCHA BALANÇA DIANT - PARTE TRASEIRA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0109', 'nome' => 'BUCHA BALANÇA DIANT POST. GM MONTANA - AXIOS', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0110', 'nome' => 'BUCHA BALANCA G', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0111', 'nome' => 'BUCHA BALANCA M', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0112', 'nome' => 'BUCHA COLUNA DIREÇÃO VW 10160', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0113', 'nome' => 'BUCHA DA BALANCA PARTE DA FRENTE STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0114', 'nome' => 'BUCHA DA BARRA ESTABILIZADORA STRADA 21 1163 - SAMPEL', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0115', 'nome' => 'BUCHA ESTABILIZADORA GM MONTANA - MOBESANI', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0116', 'nome' => 'BUCHA MAIOR DA BANDEJA STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0117', 'nome' => 'BUCHA OLHAL ESTAB DT VW 10160', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0118', 'nome' => 'BUCHAS DA BARRA ESTABILIZADORA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0119', 'nome' => 'BUCHAS PARA SUSPENSÃO AX-112753 - MOBI 2021 - AXIOS', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0145', 'nome' => 'COIFA HOMOCINETICA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0146', 'nome' => 'COIFA HOMOCINETICA EXT GM S10', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0147', 'nome' => 'COIFA LADO CAIXA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0164', 'nome' => 'COXIM AMORTEC DIANT  STRADA 2021 - DIVICAR', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0165', 'nome' => 'COXIM AMORTEC DIANT  STRADA 2021 - NAKATA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0170', 'nome' => 'COXIM SUPERIOR AMORTECEDOR DIANT STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0273', 'nome' => 'JG EM BUCHAMENTO S/ PINO VW 10160', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0295', 'nome' => 'KIT AMORTEC DIANT', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0296', 'nome' => 'KIT AMORTEC DIANT COXIM C/ROL+BAT+COIFA AX-442618 MOBI 2021 - AXIOS', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0297', 'nome' => 'KIT AMORTEC DIANT STRADA 2021 - DIVICAR', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0298', 'nome' => 'KIT AMORTEC MOBI 2021 SK143S - SAMPEL', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0299', 'nome' => 'KIT AMORTEC UNO/PALIO  TRAS', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0300', 'nome' => 'KIT BATENTE E COIFA AMORTEC DIANT STRADA 2021 - DIVICAR', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0304', 'nome' => 'KIT DE BATENTE INFERIORES DIANT STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0391', 'nome' => 'MOLA  PATIM PICINICA CARRETA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0450', 'nome' => 'PIVÔ - LADO ESQUERDO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0453', 'nome' => 'PIVÔ DE SUSP', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0455', 'nome' => 'PIVÔ SUSP MOBI 2021 CRAVEJADO N6058 - NAKATA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0681', 'nome' => 'TERMINAL DE DIREÇÃO LE', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0684', 'nome' => 'TERMINAL OLHAL', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0718', 'nome' => 'BUCHA DA BANDEJA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0718', 'nome' => 'BALANÇAS COM PIVO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0719', 'nome' => 'TERMINAL DE DIREÇÃO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0723', 'nome' => 'BUCHAS DA BALANÇA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0724', 'nome' => 'TOP KIT DIANT. (BATENTE/COXIM C/ROLAMENTO/COIFA)', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0730', 'nome' => 'BUCHAS DAS BALANÇA DIANT.', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0731', 'nome' => 'BUCHAS DA BALANÇA TRAS.', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0761', 'nome' => 'MOLA PARABOLICA REF. ACCELO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0767', 'nome' => 'BUCHA DT ACCELO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0770', 'nome' => 'TERMINAL DE ENCAIXE COM TRAVA 1.5 MM FEMEA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0772', 'nome' => 'MOLA DT 3  ACCELO 1016 MOBRASMA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0777', 'nome' => 'AMORTECEDOR TRAS.TITAN 150', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0783', 'nome' => 'BALANÇA SUSPENSAO C/BUHAS S/PIVO C/BARRA ESTABILIZADORA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0786', 'nome' => 'BIELETA DI 312679 SIENA MOBI', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0792', 'nome' => 'BALANÇA DIANTEIRA D.COMPL. C/PIVO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0798', 'nome' => 'KIT AMORTECEDOR DIANTEIRO BATENTE COIFA COXIM ROLAMENTO LD', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0799', 'nome' => 'KIT AMORTECEDOR DIANTEIRO BATENTE COIFA COXIM ROLAMNETO LE', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0800', 'nome' => 'BIELETA SUSPENSAO DIANTEIRA DIREITA ESQUERDA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0801', 'nome' => 'BALANÇA SUSPENSÃO LD C/BUCHA S/PIVO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0802', 'nome' => 'BALANÇA SUSPENSÃO LE C/BUCHA S/PIVO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0810', 'nome' => 'COIFA DA SELETORA FI 001', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0822', 'nome' => 'AMORTECEDOR DIANTEIRO - STRADA ( LD )', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0823', 'nome' => 'AMORTECEDOR DIANTEIRO - STRADA ( LE )', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0825', 'nome' => 'TERMINAL RETO DKO TB 12 MM FEMEA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0827', 'nome' => 'TERMINAL 90 LONGO FEMEA DKO TB 16MM M24X1,5 X 1/2', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0830', 'nome' => 'TERMINAL 90 FEMEA DKO TB 16MM M24X1,5 X 1/2', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0834', 'nome' => 'MOLA PLASTICA - 20 MM', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0860', 'nome' => 'BATENTE FIAT DOBLO 02 AMORT TRAS', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0864', 'nome' => 'BUCHAS TRAS. (MAIOR ) BALANÇA - D', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0865', 'nome' => 'BIELETAS DIANTEIRA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0866', 'nome' => 'BUCHAS BARRA ESTABILIZADORA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0878', 'nome' => 'BARRA AXIAL L/E - STRADA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0907', 'nome' => 'BUCHAS CALÇO TRASEIRO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0908', 'nome' => 'BATENTE DIANTEIRO CABINE', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0957', 'nome' => 'BUCHAS DA BARRA ESTABILIZADORA', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0978', 'nome' => 'TOP KIT DO AMORTECEDOR DIANT.', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0980', 'nome' => 'COIFA DO CAMBIO LADO INTERNO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0981', 'nome' => 'BATENTE TRASEIRO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0986', 'nome' => 'TOP KIT DIANT. (BATENTE/COXIM C/ROLAMENTO)', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0987', 'nome' => 'KIT COM 4 BUCHAS DA BAL. (MAIORES E MENORES)', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0988', 'nome' => 'COIFA HOMOCINETICA LADO RODA L/E', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-0992', 'nome' => 'COIFA LADO ESQUERDO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-1037', 'nome' => 'BUCHAS EIXO TRASEIRO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-1038', 'nome' => 'COIFA HOMOCINETICA LADO RODA L/D', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-1078', 'nome' => 'BUCHA DO ESTABILIZADOR', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-SUS-1092', 'nome' => 'BUCHAS DA BARRA DE DIREÇÃO', 'categoria' => 'suspensao'],
    ['codigo' => 'IMP-TRA-0052', 'nome' => 'ANEL SINC CAMBIO FSO4505C 5', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0053', 'nome' => 'ANEL SINCR CAMBIO FSO4504 3 4 5', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0054', 'nome' => 'ANEL SINCR CAMBIO FSO4505 1 2', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0058', 'nome' => 'ATUADOR EMBREAGEM GM S10/', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0123', 'nome' => 'CABO ENGATE CAMBIO GM CORSA/CELTA 05-14 - Bilbao', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0166', 'nome' => 'COXIM CAMBIO - STRADA', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0171', 'nome' => 'CUBO COM ROLAMENTOS', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0259', 'nome' => 'GRAXA LUBRAX AUTOLITH 2 ROLAMENTO 1KG', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0264', 'nome' => 'HOMOCINETICA -STRADA', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0306', 'nome' => 'KIT EMBREAGEM - STRADA', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0307', 'nome' => 'KIT EMBREAGEM GM S10 S.8 12/TDI', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0308', 'nome' => 'KIT EMBREAGEM MB ACCELO 815/1016/1316 MOTOR OM924LA 362MM', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0309', 'nome' => 'KIT EMBREAGEM MOBI', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0310', 'nome' => 'KIT EMBREAGEM STRADA 2021 619.3015.000 - LUK', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0313', 'nome' => 'KIT HOMOCINETICA LADO RODA - STRADA', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0316', 'nome' => 'KIT ROLAMENTO RODA TRAS GM CLASSIC 54010K - CORTECO', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0549', 'nome' => 'ROLAMENTO PONTA ENTALHADO ZF S5-420 FSO4505C 816E/916E', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0550', 'nome' => 'ROLAMENTO RODA DIANT MOBI 2021 VKBC 3577', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0725', 'nome' => 'CALÇO DO CAMBIO', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0738', 'nome' => 'CILINDRO MESTRE EMBREAGEM', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0763', 'nome' => 'ROLAMENTO DIANT CARRETEL MENOR', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0785', 'nome' => 'COXIM CAMBIO', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0786', 'nome' => 'ABRAÇADEIRA HOMOCINETICA', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0793', 'nome' => 'CALÇO (SUPORTE) DA CX DE CAMBIO (RAQUETE)', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0793', 'nome' => 'KIT EMBREAGEM - 3400 001 286 80S', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0795', 'nome' => 'SERVO EMBREAGEM - 464344', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0795', 'nome' => 'KIT DE EMBREAGEM C/ ATUADOR', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0796', 'nome' => 'CILINDRO PEDAL DE EMBREAGEM', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0806', 'nome' => 'ROLAMENTO TRASEIRO', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-0997', 'nome' => 'ROLAMENTO DIANTEIRO', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-1022', 'nome' => 'REPARO ALAVANCA CAMBIO', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-1088', 'nome' => 'KIT ROLAMENTO', 'categoria' => 'cambio'],
    ['codigo' => 'IMP-TRA-2000', 'nome' => 'CAMBIO DE MARCHA C/ CABO COMPLETO', 'categoria' => 'cambio']
];

$inseridos = 0;
$erros = 0;

foreach ($pecas as $peca) {
    try {
        $sql = "INSERT INTO FF_Pecas (codigo, nome, categoria, tipo, custo_medio, estoque_minimo, unidade, ativo, created_at)
                VALUES (:codigo, :nome, :categoria, 'original', 0.00, 1, 'UN', 1, NOW())
                ON DUPLICATE KEY UPDATE nome = VALUES(nome)";

        $stmt = $pdo->prepare($sql);
        $stmt->execute([
            ':codigo' => $peca['codigo'],
            ':nome' => $peca['nome'],
            ':categoria' => $peca['categoria']
        ]);
        $inseridos++;
    } catch (Exception $e) {
        $erros++;
    }
}

echo json_encode([
    'success' => true,
    'inseridos' => $inseridos,
    'erros' => $erros,
    'total' => count($pecas)
]);
